# Generated by Django 4.1.6 on 2023-07-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('brand', models.CharField(max_length=16, verbose_name='Производитель')),
                ('price', models.IntegerField(max_length=5, verbose_name='')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
