# Generated by Django 4.1.6 on 2023-07-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_images_product_preview_alter_product_brand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='media/', verbose_name='Изображение')),
                ('name', models.CharField(max_length=30, null=True, verbose_name='Название')),
                ('brand', models.CharField(max_length=16, null=True, verbose_name='Производитель')),
                ('price', models.IntegerField(max_length=5, null=True, verbose_name='Цена')),
                ('preview', models.ImageField(null=True, upload_to='products/preview/', verbose_name='Изображения для предпросмотра')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.AlterField(
            model_name='images',
            name='images',
            field=models.ImageField(upload_to='products/pictures/', verbose_name='Изображения'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='products',
            name='import_img',
            field=models.ManyToManyField(blank=True, null=True, to='app.images'),
        ),
    ]
