# Generated by Django 4.1.6 on 2023-07-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_products_alter_images_images_delete_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.CharField(max_length=500, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='products',
            name='specifications',
            field=models.CharField(max_length=1800, null=True, verbose_name='Характеристики'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(null=True, upload_to='products/pictures', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Цена'),
        ),
    ]
